version: "3"
services:
  aspnet:
    image: wayhowen/devoops:latest
    ports:
      - "80:80"
    network:
      - minitwit
    restart: always
    deploy: 
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s

networks:
  minitwit:
    driver: overlay

